### ISSUE TITLE
Eventos anteriores

### ISSUE THREAD

**Issue by miguel-mx** [lugetego/drupal-site#25]
Opción para ver los eventos anteriores

**Comment by miguel-mx** [comment]
-------- Original Message --------
Subject: Re: Ares de investigacion pagina de internet
Date: 2018-02-08 16:08
From: "Jose A. Zapata" <zapata@matmor.unam.mx>
To: Ferran Valdez <ferran@matmor.unam.mx>
Cc: academicos@matmor.unam.mx, Miguel Angel Magana <miguel@matmor.unam.mx>, Luis Gerardo Tejero <gerardo@matmor.unam.mx>, coppelia@matmor.unam.mx

Hola. 

Otra observación es que antes era muy fácil encontrar los eventos anteriores y ahora no sé cómo hacerlo. 

Saludos. 

José Antonio

**Comment by miguel-mx** [comment]
https://www.drupal.org/node/1159786

**Comment by lugetego** [comment]
Ubicación de la liga a /eventos-anteriores
Captura de información de los eventos pasados ubicados en
http://gaspacho.matmor.unam.mx/matmor/en/congresos-y-talleres
http://gaspacho.matmor.unam.mx/matmor/eventos/anteriores

**Comment by miguel-mx** [comment]
Luis Gerardo creó la vista para eventos anteriores.
http://matmor.unam.mx/es/eventos-anteriores
